syntax on

set number

set tabstop=4
set shiftwidth=4
set expandtab

set smartindent
set autoindent

function! ResetTitle()
    " disable vim's ability to set the title
    exec "set title t_ts='' t_fs=''"

    " and restore it to 'bash'
    exec ":!echo -e '\033kbash\033\\'\<CR>"
endfunction

au VimLeave * silent call ResetTitle()

let &titlestring = "vim(" . expand("%:t") . ")"
let &titlestring =  expand("%:t")
if &term == "screen"
  set t_ts=k
  set t_fs=\
endif
if &term == "screen" || &term == "xterm"
  set title
endif
